return {
["TROPHY FROM HANS"]="汉斯战利品",
["TROPHY FROM BRANDON"]="布兰登战利品",
["string.upper(self.type"]="",
["MONEY "]="金钱",
["EQUIPPED"]="装备",
["self.item.name"]="",
["TROPHY FROM MASTER YUEN"]="袁大师战利品",
["TBA"]="待定",
["STACK "]="数量",
["This mysterious skull keeps emiting ghostly light."]="神秘的骷髅，散发出诡异的光芒",
["This ring is boiling hot, the force of life in within."]="这枚戒指散发出神秘的热量。生命的力量在其间涌动。",
["The spirit lies within."]="天人合一，无所不破。",
["Move, I don't want to kill you."]="请让开。我不想杀了你。",
["I pledged my sword to Master Yuen and I am here to stop you."]="我以我的剑向袁大师宣誓，我会阻止你前进。",
["Amitabha."]="阿弥陀佛。",
["I've waited you long enough."]="我等了你很久了。",
["Hans? Why are you in my way?"]="汉斯？你怎么会在这里？",
["Hans"]="汉斯",
["River"]="江河",
["Every one of us is but a slave to karma, River. May your guns be blessed."]="我们都只是命运的奴隶，江河。希望佛祖保佑你的武器。",
[' : ']="：",
}
